# Generated by Django 4.1.2 on 2022-10-07 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='director',
            old_name='ID',
            new_name='id',
        ),
    ]
