# Generated by Django 4.1.2 on 2022-11-10 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudio', '0002_rename_id_director_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guionista',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
        ),
    ]
