# Generated by Django 4.1.2 on 2022-11-11 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estudio', '0003_guionista'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('Director', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='estudio.director', verbose_name='Director')),
                ('Guionista', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='estudio.guionista', verbose_name='Guionista')),
            ],
        ),
    ]
